# 1.i think i will Collect user details using input() first
full_name = input("Enter your full name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
favorite_language = input("Enter your favorite programming language: ")
programming_goal = input("Enter your programming goal: ")
# 2. Display formatted output
print("\n" + "=" * 40)
print("        STUDENT INTRODUCTION")
print("=" * 40)
print(f"My name is {full_name}.")
print(f"I am {age} years old.")
print(f"I live in {city}.")
print(f"I study {department} at {university}.")
print(f"My favorite programming language is {favorite_language}.")
print("My programming goal:")
print(f"{programming_goal}.")
print("=" * 40)