full_name = input("Enter full name: ")
student_id = input("Enter student ID: ")
age = int(input("Enter age: "))  
city = input("Enter city: ")
university = input("Enter university: ")
department = input("Enter department: ")
email = input("Enter email: ")
phone = input("Enter phone number: ")
fav_language = input("Enter favorite programming language: ")
goal = input("Enter programming goal: ")


print("\n" + "=" * 50)
print("              AKIBA STUDENT PROFILE")
print("=" * 50)
print(f"Name:               {full_name}")
print(f"Student ID:         {student_id}")
print(f"Age:                {age}")
print(f"City:               {city}")
print(f"University:         {university}")
print(f"Department:         {department}")
print(f"Email:              {email}")
print(f"Phone:              {phone}")
print(f"Favorite Language:   {fav_language}")
print("------------------------------------------------")
print("Programming Goal:")
print(f"{goal}")
print("=" * 50)